# Project information
site_name: Spunky Bot
site_url: https://docs.spunkybot.de
site_description: Multi-platform administration and RCON tool for Urban Terror
site_author: Alexander Kress

# Copyright
copyright: 'Copyright &copy; 2020 Alexander Kress'

# Repository
repo_url: https://github.com/SpunkyBot/spunkybot-docs
edit_uri: blob/main/docs/

# Theme
theme:
    name: readthedocs
    include_homepage_in_sidebar: false
    language: en
    custom_dir: theme/

# https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
use_directory_urls: false

# Content
nav:
- Getting Started:
    - Features: getting-started/features.md
    - Installation Guide: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Bot Settings: getting-started/settings.md
- User Guide:
    - User Roles and Groups: user-guide/user-roles-groups.md
    - Bot Commands: user-guide/commands.md
    - Player Identification: user-guide/identification.md
    - Duration Syntax: user-guide/duration.md
    - Frequently Asked Questions: user-guide/faq.md
- Community:
    - Reporting Bugs and Requesting Features: community/report-bugs-features.md
    - Contributing Guidelines: community/contributing.md
    - Checksum and Signature Verification: community/checksum-verification.md
    - Releases: community/releases.md
    - License: community/license.md
    - Code of Conduct: community/code-of-conduct.md
    - index.md

# Extensions
markdown_extensions:
    - toc:
        permalink: '#'
    - admonition
extra_css:
    - css/extra.css
