name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Python 3.8
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U mkdocs
          mkdocs --version

      - name: Build docs
        run: |
          mkdocs build --clean --strict

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          path: site
